services:
  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: pdf-service
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "7100:3000"
    environment:
      - GOTENBERG_CHROMIUM_MAX_QUEUE_SIZE=10
      - GOTENBERG_CHROMIUM_RESTART_AFTER=50
      - GOTENBERG_CHROMIUM_AUTO_START=true
      - GOTENBERG_LIBREOFFICE_AUTO_START=true
      - GOTENBERG_LIBREOFFICE_RESTART_AFTER=10
      - GOTENBERG_API_TIMEOUT=30s
      - API_ENABLE_BASIC_AUTH=true
      - GOTENBERG_API_BASIC_AUTH_USERNAME=${GOTENBERG_USER}
      - GOTENBERG_API_BASIC_AUTH_PASSWORD=${GOTENBERG_PASS}
      - GOTENBERG_LOG_LEVEL=info
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M