http:
  routers:
    gotenberg:
      entryPoints:
        - web
      rule: "PathPrefix(`/`)"
      service: gotenberg
      middlewares:
        - pdf-ratelimit

  services:
    gotenberg:
      loadBalancer:
        servers:
          - url: "http://pdf-service:3000"

  middlewares:
    pdf-ratelimit:
      rateLimit:
        average: 10
        burst: 20
        period: 1s
        sourceCriterion:
          ipStrategy:
            depth: 1
